import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';
import { writeFileSync } from 'fs';
import { resolve } from 'path';

/**
 * Vite plugin: generates public/firebase-messaging-sw.js at build time.
 *
 * ARCHITECTURE — Why Firebase SDK is NOT imported in the SW:
 *
 * The Firebase Compat SDK (firebase-app-compat + firebase-messaging-compat)
 * calls the Firebase Installations API on initialization. When called from
 * a Service Worker context, the HTTP request has NO Referer header (SWs have
 * their own origin, not the page's). This causes Google Cloud API key
 * "Websites" restrictions to block the request with 403 PERMISSION_DENIED —
 * even with the correct domain in the allowed list.
 *
 * Fix: getToken() runs ONLY from the page context (usePushNotifications.js),
 * where the Referer header IS the page URL and API key restrictions work.
 * The SW only listens for 'push' events (raw FCM delivery) and shows
 * notifications — no Firebase SDK needed for this.
 */
function firebaseMessagingSWPlugin(env) {
  const projectId = env.VITE_FIREBASE_PROJECT_ID || 'schoolpro-d95a8';

  const swContent = `
// ============================================================
// firebase-messaging-sw.js — SchoolOS+ Service Worker
// AUTO-GENERATED by vite.config.js plugin — DO NOT edit manually.
//
// Responsibilities:
//  1. Handle raw FCM 'push' events (background/closed tab notifications)
//  2. Handle notification click navigation
//  3. PWA app shell caching for offline support
//
// NOTE: Firebase SDK is intentionally NOT imported here.
// See vite.config.js for the full explanation.
// ============================================================

const CACHE_NAME   = 'schoolos-sw-v5';
const PROJECT_ID   = "${projectId}";
const PRECACHE_URLS = ['/', '/index.html', '/manifest.webmanifest', '/icons/icon-192.png', '/icons/icon-512.png'];

// ── Install ───────────────────────────────────────────────────────────────────
self.addEventListener('install', (event) => {
  self.skipWaiting(); // Take over immediately — no waiting for old SW to die
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) =>
      cache.addAll(PRECACHE_URLS).catch((e) => console.warn('[sw] Pre-cache error (non-fatal):', e))
    )
  );
  console.log('[sw] Installed. Cache:', CACHE_NAME);
});

// ── Activate ──────────────────────────────────────────────────────────────────
self.addEventListener('activate', (event) => {
  event.waitUntil(
    Promise.all([
      // Delete all old caches
      caches.keys().then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
      ),
      // Immediately control all open tabs
      self.clients.claim(),
    ]).then(() => console.log('[sw] ✅ Activated. Controlling all clients.'))
  );
});

// ── Push event ────────────────────────────────────────────────────────────────
// FCM sends raw push events when the app is closed or the tab is in background.
// We must show a notification here — the page is unavailable to do it.
// The payload follows FCM v1 format: { notification: {title, body}, data: {...} }
self.addEventListener('push', (event) => {
  let payload = {};
  try {
    payload = event.data ? event.data.json() : {};
  } catch (e) {
    try { payload = { notification: { title: event.data?.text() || 'SchoolOS+' } }; } catch (_) {}
  }

  const title = payload.notification?.title || payload.data?.title || 'SchoolOS+ Alert';
  const body  = payload.notification?.body  || payload.data?.body  || '';
  const route = payload.data?.route || payload.fcmOptions?.link || '/';

  console.log('[sw] Push received. Title:', title);

  event.waitUntil(
    self.registration.showNotification(title, {
      body,
      icon:               '/icons/icon-192.png',
      badge:              '/icons/icon-72.png',
      tag:                'schoolos-push',
      renotify:           true,
      requireInteraction: false,
      data:               { route },
    })
  );
});

// ── Notification click ────────────────────────────────────────────────────────
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const route = event.notification.data?.route || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      for (const client of clients) {
        if ('focus' in client) {
          client.focus();
          if ('navigate' in client) return client.navigate(route);
          return;
        }
      }
      if (self.clients.openWindow) return self.clients.openWindow(route);
    })
  );
});

// ── Message ───────────────────────────────────────────────────────────────────
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

// ── Fetch: PWA caching strategy ───────────────────────────────────────────────
self.addEventListener('fetch', (event) => {
  const { request } = event;

  // Parse URL safely
  let url;
  try { url = new URL(request.url); } catch { return; }

  // Only handle same-origin GETs — skip all cross-origin and non-GET
  if (request.method !== 'GET' || url.origin !== self.location.origin) return;

  // Never intercept SW files
  if (url.pathname.startsWith('/firebase-messaging-sw') || url.pathname === '/sw.js') return;

  // SPA navigation: network first, fall back to cached index.html (offline)
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() => caches.match('/index.html'))
    );
    return;
  }

  // Hashed Vite build assets (/assets/...): cache-first (filenames include content hash)
  if (url.pathname.startsWith('/assets/')) {
    event.respondWith(
      caches.match(request).then((cached) => {
        if (cached) return cached;
        return fetch(request).then((response) => {
          if (response && response.ok && response.status === 200) {
            const cloned = response.clone(); // Must clone BEFORE body is consumed
            caches.open(CACHE_NAME).then((c) => c.put(request, cloned)).catch(() => {});
          }
          return response;
        }).catch(() => caches.match(request)); // Offline fallback: serve from cache if available
      })
    );
    return;
  }

  // Static assets (icons, images, fonts): cache-first, network fallback
  if (/\\.(png|ico|webp|svg|woff2|woff|ttf)$/.test(url.pathname)) {
    event.respondWith(
      caches.match(request).then((cached) =>
        cached || fetch(request).catch(() => new Response('', { status: 503 }))
      )
    );
    return;
  }

  // Everything else (Supabase API, Firebase, etc.): network only
});
`.trimStart();

  function generate() {
    try {
      const outputPath = resolve('./public/firebase-messaging-sw.js');
      writeFileSync(outputPath, swContent, 'utf8');
      console.log('[vite-plugin:sw] ✅ Generated public/firebase-messaging-sw.js');
    } catch (e) {
      console.error('[vite-plugin:sw] Failed to generate SW:', e.message);
    }
  }

  return {
    name: 'firebase-messaging-sw',
    buildStart() { generate(); },
    configureServer() { generate(); },
  };
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');

  return {
    plugins: [
      react(),
      firebaseMessagingSWPlugin(env),
    ],
    server: {
      port: 3000,
      host: true,
    },
    build: {
      outDir: 'dist',
      sourcemap: false,
      emptyOutDir: true,
    },
  };
});
