import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';
import { writeFileSync } from 'fs';
import { resolve } from 'path';

/**
 * Vite plugin: generates public/firebase-messaging-sw.js at build time.
 *
 * This is the UNIFIED service worker — it handles BOTH:
 *  1. Firebase Cloud Messaging (background push notifications)
 *  2. PWA app shell caching (offline support)
 *
 * WHY unified:
 *  - Browsers only allow ONE active service worker per scope ('/').
 *  - Having sw.js AND firebase-messaging-sw.js both registered at '/' causes
 *    sw.js (with skipWaiting) to block firebase-messaging-sw.js in "waiting"
 *    state forever → PushManager.subscribe() fails with "no active SW" AbortError.
 *  - Single SW eliminates all scope conflicts and activation race conditions.
 *
 * WHY config is baked in:
 *  - Service Workers run outside the Vite bundle and cannot access import.meta.env.
 *  - loadEnv() reads .env / GitHub Secrets at build time and substitutes values directly.
 */
function firebaseMessagingSWPlugin(env) {
  const apiKey            = env.VITE_FIREBASE_API_KEY            || '';
  const authDomain        = env.VITE_FIREBASE_AUTH_DOMAIN        || '';
  const databaseURL       = env.VITE_FIREBASE_DATABASE_URL       || '';
  const projectId         = env.VITE_FIREBASE_PROJECT_ID         || 'schoolpro-d95a8';
  const storageBucket     = env.VITE_FIREBASE_STORAGE_BUCKET     || '';
  const messagingSenderId = env.VITE_FIREBASE_MESSAGING_SENDER_ID|| '';
  const appId             = env.VITE_FIREBASE_APP_ID             || '';

  const swContent = `
// ============================================================
// firebase-messaging-sw.js — SchoolOS+ Unified Service Worker
// AUTO-GENERATED by vite.config.js — DO NOT edit manually.
// Handles: Firebase Cloud Messaging + PWA offline caching.
// ============================================================
importScripts('https://www.gstatic.com/firebasejs/10.12.3/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.12.3/firebase-messaging-compat.js');

// ── Firebase config (baked in at build time) ─────────────────────────────────
const firebaseConfig = {
  apiKey:            "${apiKey}",
  authDomain:        "${authDomain}",
  databaseURL:       "${databaseURL}",
  projectId:         "${projectId}",
  storageBucket:     "${storageBucket}",
  messagingSenderId: "${messagingSenderId}",
  appId:             "${appId}",
};

// ── Firebase Messaging ────────────────────────────────────────────────────────
let messaging = null;
if (firebaseConfig.apiKey && firebaseConfig.messagingSenderId) {
  try {
    firebase.initializeApp(firebaseConfig);
    messaging = firebase.messaging();

    // Fires when the app is closed or the tab is in the background.
    messaging.onBackgroundMessage((payload) => {
      console.info('[unified-sw] Background FCM message received:', payload);
      const title = payload.notification?.title || payload.data?.title || 'SchoolOS+ Alert';
      const options = {
        body:               payload.notification?.body || payload.data?.body || '',
        icon:               '/icons/icon-192.png',
        badge:              '/icons/icon-72.png',
        tag:                'schoolos-notification',
        renotify:           true,
        requireInteraction: false,
        data:               { route: payload.data?.route || '/' },
      };
      return self.registration.showNotification(title, options);
    });

    console.info('[unified-sw] ✅ Firebase Messaging ready.');
  } catch (err) {
    console.error('[unified-sw] Firebase init failed:', err.message);
  }
} else {
  console.warn('[unified-sw] Firebase config missing — messaging disabled.');
}

// ── Notification click ────────────────────────────────────────────────────────
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const route = event.notification.data?.route || '/';
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      for (const client of clients) {
        if ('focus' in client) {
          client.focus();
          if ('navigate' in client) return client.navigate(route);
        }
      }
      if (self.clients.openWindow) return self.clients.openWindow(route);
    })
  );
});

// ── Message handler (allows page to trigger skipWaiting) ─────────────────────
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// ── PWA Caching ───────────────────────────────────────────────────────────────
const CACHE_NAME = 'schoolos-unified-v1';
const PRECACHE_ASSETS = [
  '/',
  '/index.html',
  '/manifest.webmanifest',
  '/theme-init.js',
  '/icons/icon-192.png',
  '/icons/icon-512.png',
];

self.addEventListener('install', (event) => {
  // Skip waiting immediately so this SW takes over from any old SW right away.
  // This is critical: if the old sw.js is controlling the page, skipWaiting()
  // forces this SW to activate, allowing PushManager.subscribe() to succeed.
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      console.log('[unified-sw] Pre-caching app shell');
      return cache.addAll(PRECACHE_ASSETS).catch((err) => {
        console.warn('[unified-sw] Pre-cache partial failure (non-fatal):', err.message);
      });
    })
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((names) => Promise.all(
        names
          .filter((n) => n !== CACHE_NAME)
          .map((n) => { console.log('[unified-sw] Clearing old cache:', n); return caches.delete(n); })
      ))
      .then(() => {
        console.log('[unified-sw] ✅ Activated and claiming all clients.');
        return self.clients.claim(); // Take control of all open tabs immediately
      })
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);

  // Only handle same-origin GETs
  if (request.method !== 'GET' || url.origin !== self.location.origin) return;

  // Never intercept SW files themselves (prevents caching stale SW code)
  if (url.pathname.includes('firebase-messaging-sw') || url.pathname === '/sw.js') return;

  // SPA navigation: network first, fallback to cached index.html
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() => caches.match('/index.html'))
    );
    return;
  }

  // Hashed Vite build assets — cache forever (content-addressed)
  if (url.pathname.startsWith('/assets/')) {
    event.respondWith(
      caches.match(request).then((cached) => {
        if (cached) return cached;
        return fetch(request).then((res) => {
          if (res && res.status === 200 && (res.type === 'basic' || res.type === 'cors')) {
            caches.open(CACHE_NAME).then((c) => c.put(request, res.clone()));
          }
          return res;
        });
      })
    );
    return;
  }

  // Static public assets (icons, fonts)
  if (/\\.(png|ico|webp|woff2|woff)$/.test(url.pathname)) {
    event.respondWith(
      caches.match(request).then((cached) => cached || fetch(request))
    );
    return;
  }

  // Everything else (API, Supabase, etc.): network only
});
`.trimStart();

  function generate() {
    const outputPath = resolve('./public/firebase-messaging-sw.js');
    writeFileSync(outputPath, swContent, 'utf8');
    console.log('[vite-plugin:unified-sw] ✅ Generated public/firebase-messaging-sw.js (Firebase + PWA cache)');
  }

  return {
    name: 'firebase-messaging-sw',
    buildStart() { generate(); },
    configureServer() { generate(); },
  };
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');

  return {
    plugins: [
      react(),
      firebaseMessagingSWPlugin(env),
    ],
    server: {
      port: 3000,
      host: true,
    },
    build: {
      outDir: 'dist',
      sourcemap: false,
      emptyOutDir: true,
    },
  };
});
