-- ============================================================
-- MIGRATION: v25_push_notifications.sql
-- Description: Create user_device_tokens table for FCM Push Notifications
-- Date: 2026-04-26
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- 1. Create the table
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_device_tokens (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  school_id     uuid REFERENCES public.school_settings(school_id) ON DELETE SET NULL,
  fcm_token     text NOT NULL,
  platform      text NOT NULL CHECK (platform IN ('android', 'ios', 'web')),
  device_name   text,               -- Optional: e.g. "Redmi Note 12"
  last_seen_at  timestamptz NOT NULL DEFAULT now(),
  created_at    timestamptz NOT NULL DEFAULT now(),

  -- Ensure one FCM token is linked to at most one user.
  -- If the same physical device is re-used by a different user,
  -- the old row is overwritten by the upsert.
  CONSTRAINT uq_user_fcm_token UNIQUE (user_id, fcm_token)
);

-- ────────────────────────────────────────────────────────────
-- 2. Indexes for fast lookups (Edge Functions will query by user_id / school_id)
-- ────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_user_device_tokens_user_id
  ON public.user_device_tokens(user_id);

CREATE INDEX IF NOT EXISTS idx_user_device_tokens_school_id
  ON public.user_device_tokens(school_id);

-- ────────────────────────────────────────────────────────────
-- 3. Enable Row Level Security
-- ────────────────────────────────────────────────────────────
ALTER TABLE public.user_device_tokens ENABLE ROW LEVEL SECURITY;

-- ────────────────────────────────────────────────────────────
-- 4. RLS Policies
-- ────────────────────────────────────────────────────────────

-- 4a. Users can INSERT / UPDATE their OWN tokens only.
CREATE POLICY "users_manage_own_tokens"
  ON public.user_device_tokens
  FOR ALL                          -- covers INSERT, UPDATE, DELETE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- 4b. Users can SELECT their own tokens (useful for debugging / deduplication).
CREATE POLICY "users_read_own_tokens"
  ON public.user_device_tokens
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

-- 4c. Service role (used by Edge Functions) can read ALL tokens to send notifications.
--     This policy is implicitly covered because service_role bypasses RLS.
--     No extra policy needed for the Edge Function backend.

-- ────────────────────────────────────────────────────────────
-- 5. Helper RPC: upsert_device_token
--    Called from the React hook. Handles insert-or-update in one atomic call.
--    Using SECURITY DEFINER so RLS doesn't block the upsert path.
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.upsert_device_token(
  p_user_id    uuid,
  p_school_id  uuid,
  p_fcm_token  text,
  p_platform   text,
  p_device_name text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.user_device_tokens
    (user_id, school_id, fcm_token, platform, device_name, last_seen_at)
  VALUES
    (p_user_id, p_school_id, p_fcm_token, p_platform, p_device_name, now())
  ON CONFLICT (user_id, fcm_token)
  DO UPDATE SET
    school_id     = EXCLUDED.school_id,
    platform      = EXCLUDED.platform,
    device_name   = EXCLUDED.device_name,
    last_seen_at  = now();
END;
$$;

-- Grant execute to authenticated users
GRANT EXECUTE ON FUNCTION public.upsert_device_token TO authenticated;

-- ────────────────────────────────────────────────────────────
-- 6. Comments for documentation
-- ────────────────────────────────────────────────────────────
COMMENT ON TABLE public.user_device_tokens IS
  'Stores FCM push notification tokens per user per device. Used by Supabase Edge Functions to send targeted push notifications.';

COMMENT ON COLUMN public.user_device_tokens.fcm_token IS
  'The native FCM registration token generated by Capacitor Push Notifications on Android/iOS.';

COMMENT ON COLUMN public.user_device_tokens.platform IS
  'Platform identifier: android | ios | web';

COMMENT ON FUNCTION public.upsert_device_token IS
  'Atomically inserts or updates an FCM token for a user device. Called by the React usePushNotifications hook after login.';
